[package]
name = "servman"
version = "0.1.0"
authors = ["arioz0330 <arios2@live.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.6"
reqwest = {version = "0.10.10", features = ["json"]}
tokio = {version = "0.2.*", features = ["full"] }
serde = { version = "1.0.118",default-features = false, features = ["derive"] }
serde-xml-rs = "0.4.0"
parking_lot = { version = "0.11.1", features = ["nightly"] }
serde_json = "1.0.60"
lazy_static = "1.4.0"

[profile.release]
lto = 'thin'
panic = 'abort'
codegen-units = 1

[profile.bench]
lto = 'thin'
codegen-units = 1